### ISSUE TITLE
Nice work. When would u release your training code? Hope u could release as soon as possible...

### ISSUE THREAD

**Issue by TyroneLi** [Shathe/SemiSeg-Contrastive#1]

**Comment by TyroneLi** [comment]
> _No description provided._

Hi~when would u plan to release?

**Comment by Shathe** [comment]
I am cleaning it out. For sure I will release it before the conference. I do not think this month I will be able to, so it will be probably between September and early October :)

**Comment by TyroneLi** [comment]
> I am cleaning it out. For sure I will release it before the conference. I do not think this month I will be able to, so it will be probably between September and early October :)
