### ISSUE TITLE
A confusing details in the paper 

### ISSUE THREAD

**Issue by Chic-J** [Shathe/SemiSeg-Contrastive#2]
Hi, I have read the paper and it is great. But i found an error(maybe?)
![image](https://user-images.githubusercontent.com/41068484/132509866-3b60d414-3b1d-4953-9955-d2b804b8bf99.png)
According to the paper, vector Pc is from Student Network, and Z'c is from Teacher Network, which is opposite in the figure. So this would be confusing.Do i misread or just an error in the figure?

**Comment by Shathe** [comment]
So please, notice the weights that are being used in the text shen f is applied:
Weights ξ are used by the teacher and, θ by the student.
Vectors Pc are obtained by the student and Z' is obtained by the teacher as you correctly mentioned that is in the paper.
In the figure, the right part is the teacher network that is generating Z', in the left the student generates P

**Comment by Chic-J** [comment]
> So please, notice the weights that are being used in the text shen f is applied:
> Weights ξ are used by the teacher and, θ by the student.
> Vectors Pc are obtained by the student and Z' is obtained by the teacher as you correctly mentioned that is in the paper.
> In the figure, the right part is the teacher network that is generating Z', in the left the student generates P


thanks for your reply.
and i have 2 more questions.
1. when will the codes release? i can't wait to see~
2. I wonder why the features in the memory bank come from Teacher instead of Student. As i see, the features of labeled data could also created by the Student and using Teacher to create features of labeled data increases the computation. so why not use features from Student into the memory bank.?

**Comment by Shathe** [comment]
The code will be available at the end of this month probably, before the conference.

Regarding the second question, the features can obtained by bith student and teacher: see Tablr 8 (Ablation study of our contrastive learning module main components), but with the teacher you get a little higher performance
